apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: database-credentials
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: database-credentials
  data:
  - secretKey: POSTGRES_DB 
    remoteRef: 
      key: harbor/database
      property: POSTGRES_DB
  - secretKey: POSTGRES_USER
    remoteRef: 
      key: harbor/database
      property: POSTGRES_USER
  - secretKey: POSTGRES_PASSWORD
    remoteRef: 
      key: harbor/database
      property: POSTGRES_PASSWORD
  - secretKey: POSTGRES_HOST
    remoteRef: 
      key: harbor/database
      property: POSTGRES_HOST
  - secretKey: POSTGRES_PORT
    remoteRef: 
      key: harbor/database
      property: POSTGRES_PORT
  - secretKey: password
    remoteRef: 
      key: harbor/database
      property: POSTGRES_PASSWORD